# SPDX-License-Identifier: GPL-2.0

dtb-$(CONFIG_ARCH_MXC) += armstonemx8mp.dtb
dtb-$(CONFIG_ARCH_MXC) += picocoremx8mm-lpddr4.dtb \
			  picocoremx8mm-lpddr4-lcdif-tc358764-g070y2-l01.dtb \
			  picocoremx8mm-lpddr4-lcdif-tc358775-j070wvtc0211.dtb \
			  picocoremx8mm-lpddr4-lcdif-g050tan01.dtb \
			  picocoremx8mm-lpddr4-lcdif-adp-mipi2mipi1-ee0350et-2cp.dtb \
			  picocoremx8mm-lpddr4-lcdif-adp-mipi2rgb.dtb \
			  picocoremx8mm-lpddr4-lcdif-rgt070qyh-13cp.dtb \
			  tbs2.dtb \
			  tbs2-lcdif-adp-mipi2rgb-etm0350.dtb \
			  picocoremx8mm-ddr3l.dtb \
			  picocoremx8mm-ddr3l-lcdif-tc358775-g133han01.dtb \
			  picocoremx8mm-ddr3l-lcdif-tc358775-j070wvtc0211.dtb \
			  picocoremx8mm-ddr3l-lcdif-g050tan01.dtb \
			  picocoremx8mm-ddr3l-lcdif-adp-mipi2lvds1-j070wvtc0211-single-display.dtb \
			  picocoremx8mm-ddr3l-lcdif-adp-mipi2lvds1-g133han01.dtb \
			  picocoremx8mm-ddr3l-lcdif-adp-mipi2mipi1-ee0350et-2cp.dtb \
			  picocoremx8mm-ddr3l-lcdif-adp-mipi2rgb.dtb \
			  picocoremx8mm-ddr3l-lcdif-rgt070qyh-13cp.dtb
dtb-$(CONFIG_ARCH_MXC) += efusmx8x.dtb \
			  efusmx8x-lcdif-j070wvtc0211.dtb \
			  efusmx8x-lcdif-rgt070qyh-13cp.dtb
dtb-$(CONFIG_ARCH_MXC) += picocoremx8mn-lpddr4.dtb \
			  picocoremx8mn-lpddr4-lcdif-tc358775-g070y2-l01.dtb \
			  picocoremx8mn-lpddr4-lcdif-tc358775-j070wvtc0211.dtb \
			  picocoremx8mn-lpddr4-lcdif-g050tan01.dtb \
			  picocoremx8mn-lpddr4-lcdif-adp-mipi2lvds1-j070wvtc0211-single-display.dtb \
			  picocoremx8mn-lpddr4-lcdif-adp-mipi2lvds1-g133han01.dtb \
			  picocoremx8mn-lpddr4-lcdif-adp-mipi2mipi1-ee0350et-2cp.dtb \
			  picocoremx8mn-ddr3l.dtb \
			  picocoremx8mn-ddr3l-lcdif-tc358775-g133han01.dtb \
			  picocoremx8mn-ddr3l-lcdif-tc358775-j070wvtc0211.dtb \
			  picocoremx8mn-ddr3l-lcdif-adp-mipi2lvds1-g133han01.dtb \
			  picocoremx8mn-ddr3l-lcdif-adp-mipi2mipi1-ee0350et-2cp.dtb \
			  picocoremx8mn-ddr3l-lcdif-adp-mipi2rgb.dtb \
			  picocoremx8mn-ddr3l-lcdif-adp-mipi2lvds1-j070wvtc0211-single-display.dtb
dtb-$(CONFIG_ARCH_MXC) += picocoremx8mp.dtb \
			  picocoremx8mp-lcdif-adp-mipi2lvds1-j070wvtc0211-single-display.dtb \
			  picocoremx8mp-lcdif-adp-mipi2mipi1-ee0350et-2cp.dtb \
			  picocoremx8mp-lcdif-j070wvtc0211.dtb \
			  picocoremx8mp-lcdif-g133han01.dtb \
			  picocoremx8mp-adp-aud1.dtb \
			  picocoremx8mp-basler-isp.dtb \
			  picocoremx8mpr2-basler-isp.dtb
dtb-$(CONFIG_ARCH_MXC) += picocoremx8mmr2-lpddr4.dtb \
			  picocoremx8mmr2-lpddr4-lcdif-tc358764-g070y2-l01.dtb \
			  picocoremx8mmr2-lpddr4-lcdif-tc358775-j070wvtc0211.dtb \
			  picocoremx8mmr2-lpddr4-lcdif-g050tan01.dtb \
			  picocoremx8mmr2-lpddr4-lcdif-adp-mipi2mipi1-ee0350et-2cp.dtb \
			  picocoremx8mmr2-lpddr4-lcdif-adp-mipi2rgb.dtb
dtb-$(CONFIG_ARCH_MXC) += picocoremx8mpr2.dtb \
			  picocoremx8mpr2-lcdif-j070wvtc0211.dtb \
			  picocoremx8mpr2-lcdif-j070wvtc0211.dtb \
			  picocoremx8mpr2-lcdif-adp-mipi2lvds1-j070wvtc0211-single-display.dtb \
			  picocoremx8mpr2-lcdif-adp-mipi2mipi1-ee0350et-2cp.dtb \
			  picocoremx8mpr2-lcdif-g133han01.dtb \
			  picocoremx8mpr2-adp-aud1.dtb
dtb-$(CONFIG_ARCH_MXC) += efusmx8mp.dtb
