# SPDX-License-Identifier: GPL-2.0
# add __symbols__ for label references
DTC_FLAGS += -@

dtb-$(CONFIG_ARCH_MXC) += armstonemx8mp.dtb \
			  armstonemx8mp-BT070L1060CS0I1AD-A.dtb \
			  armstonemx8mp-EE1010B1T-1CP.dtb
dtb-$(CONFIG_ARCH_MXC) += picocoremx8mm-lpddr4.dtb \
			  picocoremx8mm-lpddr4-lcdif-tc358764-g070y2-l01.dtb \
			  picocoremx8mm-lpddr4-lcdif-tc358775-j070wvtc0211.dtb \
			  picocoremx8mm-lpddr4-lcdif-g050tan01.dtb \
			  picocoremx8mm-lpddr4-lcdif-adp-mipi2mipi1-ee0350et-2cp.dtb \
			  picocoremx8mm-lpddr4-lcdif-adp-mipi2rgb.dtb \
			  picocoremx8mm-lpddr4-tc358775-BT070L1060CS0I1AD-A.dtb \
			  tbs2.dtb \
			  tbs2-lcdif-adp-mipi2rgb-etm0350.dtb \
			  picocoremx8mm-ddr3l.dtb \
			  picocoremx8mm-ddr3l-lcdif-tc358775-g133han01.dtb \
			  picocoremx8mm-ddr3l-lcdif-tc358775-j070wvtc0211.dtb \
			  picocoremx8mm-ddr3l-lcdif-g050tan01.dtb \
			  picocoremx8mm-ddr3l-lcdif-adp-mipi2lvds1-j070wvtc0211-single-display.dtb \
			  picocoremx8mm-ddr3l-lcdif-adp-mipi2lvds1-g133han01.dtb \
			  picocoremx8mm-ddr3l-lcdif-adp-mipi2mipi1-ee0350et-2cp.dtb \
			  picocoremx8mm-ddr3l-lcdif-adp-mipi2rgb.dtb \
			  picocoremx8mm-ddr3l-tc358775-BT070L1060CS0I1AD-A.dtb
dtb-$(CONFIG_ARCH_MXC) += efusmx8x.dtb \
			  efusmx8x-lcdif-j070wvtc0211.dtb \
			  efusmx8x-lcdif-rgt070qyh-13cp.dtb
dtb-$(CONFIG_ARCH_MXC) += picocoremx8mn-lpddr4.dtb \
			  picocoremx8mn-lpddr4-lcdif-tc358775-j070wvtc0211.dtb \
			  picocoremx8mn-lpddr4-lcdif-adp-mipi2mipi1-ee0350et-2cp.dtb \
			  picocoremx8mn-lpddr4-tc358775-BT070L1060CS0I1AD-A.dtb \
			  picocoremx8mn-ddr3l.dtb \
			  picocoremx8mn-ddr3l-lcdif-tc358775-j070wvtc0211.dtb \
			  picocoremx8mn-ddr3l-lcdif-adp-mipi2mipi1-ee0350et-2cp.dtb \
			  picocoremx8mn-ddr3l-lcdif-adp-mipi2rgb.dtb \
			  picocoremx8mn-ddr3l-tc358775-BT070L1060CS0I1AD-A.dtb
dtb-$(CONFIG_ARCH_MXC) += picocoremx8mp.dtb \
			  picocoremx8mp-lcdif-adp-mipi2lvds1-j070wvtc0211-single-display.dtb \
			  picocoremx8mp-lcdif-adp-mipi2mipi1-ee0350et-2cp.dtb \
			  picocoremx8mp-lcdif-j070wvtc0211.dtb \
			  picocoremx8mp-lcdif-g133han01.dtb \
			  picocoremx8mp-adp-aud1.dtb \
			  picocoremx8mp-basler-isp.dtb \
			  picocoremx8mpr2-basler-isp.dtb \
			  picocoremx8mp-BT070L1060CS0I1AD-A.dtb \
			  picocoremx8mp-EE1010B1T-1CP.dtb
dtb-$(CONFIG_ARCH_MXC) += picocoremx8mmr2-lpddr4.dtb \
			  picocoremx8mmr2-lpddr4-lcdif-tc358764-g070y2-l01.dtb \
			  picocoremx8mmr2-lpddr4-lcdif-tc358775-j070wvtc0211.dtb \
			  picocoremx8mmr2-lpddr4-lcdif-g050tan01.dtb \
			  picocoremx8mmr2-lpddr4-lcdif-adp-mipi2mipi1-ee0350et-2cp.dtb \
			  picocoremx8mmr2-lpddr4-lcdif-adp-mipi2rgb.dtb \
			  picocoremx8mmr2-lpddr4-tc358775-BT070L1060CS0I1AD-A.dtb
dtb-$(CONFIG_ARCH_MXC) += picocoremx8mpr2.dtb \
			  picocoremx8mpr2-lcdif-j070wvtc0211.dtb \
			  picocoremx8mpr2-lcdif-adp-mipi2lvds1-j070wvtc0211-single-display.dtb \
			  picocoremx8mpr2-lcdif-adp-mipi2mipi1-ee0350et-2cp.dtb \
			  picocoremx8mpr2-lcdif-g133han01.dtb \
			  picocoremx8mpr2-adp-aud1.dtb \
			  picocoremx8mpr2-BT070L1060CS0I1AD-A.dtb \
			  picocoremx8mpr2-EE1010B1T-1CP.dtb
dtb-$(CONFIG_ARCH_MXC) += efusmx8mp.dtb \
			  efusmx8mp-BT070L1060CS0I1AD-A.dtb \
			  efusmx8mp-EE1010B1T-1CP.dtb \
			  efusmx8mp-ET070080DH6.dtb
dtb-$(CONFIG_ARCH_MXC) += fssmmx8mp.dtb \
			  fssmmx8mp-lcdif-j070wvtc0211.dtb \
			  fssmmx8mp-BT070L1060CS0I1AD-A.dtb \
			  fssmmx8mp-EE1010B1T-1CP.dtb
dtb-$(CONFIG_ARCH_MXC) += osm8mm.dtb \
			  osm8mm-lcdif-adp-mipi2mipi1-ee0350et-2cp.dtb
dtb-$(CONFIG_ARCH_MXC) += \
			  soldercore8ulp-bbhd.dtb
dtb-$(CONFIG_ARCH_MXC) += \
			  picocoremx8ulp.dtb \
			  picocoremx8ulp-adp-mipi2mipi1-ee0350et-2cp.dtb \
			  picocoremx8ulp-adp-mipi2lvds1-BT070L1060CS0I1AD-A.dtb
dtb-$(CONFIG_ARCH_MXC) += \
			  fs-osm-sf-mx8ulp-adp-osm-bb.dtb \
			  fs-osm-sf-mx8ulp-adp-osm-bb-ee0350et-2cp.dtb
dtb-$(CONFIG_ARCH_MXC) += \
			  picocoremx93.dtb \
			  picocoremx93-BT070L1060CS0I1AD-A.dtb \
			  picocoremx93-adp-lvds2lvds2-EE1010B1T-1CP.dtb \
			  picocoremx93-adp-mipi2mip1-ee0350et-2cp.dtb
dtb-$(CONFIG_ARCH_MXC) += \
			  fs-osm-sf-mx93-adp-osm-bb.dtb \
			  fs-osm-sf-mx93-adp-osm-bb_BT070L1060CS0I1AD-A.dtb
