obj-$(CONFIG_MTD_NAND_GPMI_NAND) += gpmi_nand.o
gpmi_nand-objs += gpmi-nand.o
gpmi_nand-objs += gpmi-lib.o
obj-$(CONFIG_MTD_NAND_GPMI_NAND_FUS) += gpmi_nand_fus.o
gpmi_nand_fus-objs += gpmi-nand-fus.o
