# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_DRM_IMX8_DC) += dc/
obj-$(CONFIG_DRM_IMX_DCSS) += dcss/
obj-$(CONFIG_DRM_IMX_CDNS_MHDP) += mhdp/
obj-$(CONFIG_DRM_IMX8MM_LCDIF) += lcdif/
obj-$(CONFIG_DRM_IMX_LCDIFV3) += lcdifv3/
obj-$(CONFIG_DRM_IMX_LCDC) += lcdc/
