# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_SOC_IMX6Q) += \
	netdcua9dl.dtb \
	picomoda9dl.dtb \
	efusa9dl.dtb \
	efusa9r2dl.dtb \
	armstonea9dl.dtb \
	armstonea9r2dl.dtb \
	armstonea9r3dl.dtb \
	armstonea9r4dl.dtb \
	qblissa9dl.dtb \
	qblissa9r2dl.dtb \
	netdcua9q.dtb \
	picomoda9q.dtb \
	efusa9q.dtb \
	efusa9r2q.dtb \
	armstonea9q.dtb \
	armstonea9r2q.dtb \
	armstonea9r3q.dtb \
	armstonea9r4q.dtb \
	qblissa9q.dtb \
	qblissa9r2q.dtb
dtb-$(CONFIG_SOC_IMX6SX) += \
	efusa9x.dtb \
	efusa9xr2.dtb \
	picocoremx6sx.dtb \
	picocoremx6sxr2.dtb \
	vc600.dtb \
	bema9x.dtb \
	picocoma9x.dtb \
	cont1.dtb \
	vand3.dtb
dtb-$(CONFIG_SOC_IMX6UL) += \
	efusa7ul.dtb \
	picocom1.2.dtb \
	picocoma7.dtb \
	picocoremx6ul.dtb \
	picocoremx6ul100.dtb \
	cubea7ul.dtb \
	cube2.0.dtb \
	gar1.dtb \
	gar2.dtb \
	gar3.dtb \
	efusa7ull.dtb \
	cube2.0ull.dtb \
	picocoma7ull.dtb \
	picocoremx6ull.dtb \
	picocoremx6ull100.dtb
dtb-$(CONFIG_SOC_IMX7ULP) += \
	picocoremx7ulp.dtb

